/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redeneural;

import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TableView.TableRow;
import redeneural.LeitorCSV;

/**
 *
 * @author Tiago
 */
public class MainFrame extends javax.swing.JFrame {

    ArrayList<Double[][]> dadosTreinamento;
    ANNBackpropagation rede;
    long tempoExecucao;
    int numeroVezesTreinanda = 0;
    int neuroniosEntrada = 4;
    int neuroniosIntermediaria = 9;
    int neuroniosSaida = 9;
    NumberFormat formater = new DecimalFormat("#0.000000");

    public MainFrame() {
        initComponents();

    }

    public void iniciaComponentes() {
        // rede
        //componentes
        jTFStatusCSV.setText("Aguardando arquivo CSV");
        jTFStatusCSV.setEditable(false);
        jTFNumeroTreinamentosRealizados.setEditable(false);
        jTFErro.setEditable(false);
        jTFTempo.setEditable(false);
        jTFNumeroTreinamentos.setText("1");
        String textoExemplo = "Formato: ";
        String textoTreinamento = "";
        for (int i = 0; i < neuroniosEntrada; i++) {
            if (i < neuroniosEntrada - 1) {
                textoExemplo += "0,";
                textoTreinamento += "1,";
            } else {
                textoExemplo += "0";
                textoTreinamento += "1";
            }

        }
        jLFormatoTeste.setText(textoExemplo);
        jTFDadosTestarRede.setText(textoTreinamento);
    }

    public void zerarRede() {
        rede = new ANNBackpropagation(neuroniosEntrada, neuroniosIntermediaria, neuroniosSaida, 0.8, ActivationFunction.SIGMOID);

        jTFNumeroTreinamentosRealizados.setText("");
        jTFErro.setText("");
        jTFTempo.setText("0 ms");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTPTreinamentoRede = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFNEntrada = new javax.swing.JTextField();
        jTFNIntermediaria = new javax.swing.JTextField();
        jTFNeuroniosSaida = new javax.swing.JTextField();
        jBTDefinirNNeuronios = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFNumeroTreinamentos = new javax.swing.JTextField();
        jBTreinar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFErro = new javax.swing.JTextField();
        jTFNumeroTreinamentosRealizados = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBTCarregaCSV = new javax.swing.JButton();
        jTFStatusCSV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFTempo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTFDadosTestarRede = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTTestar = new javax.swing.JTable();
        jBtTestar = new javax.swing.JButton();
        jLFormatoTeste = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Neuronios na camada de entrada:");

        jLabel7.setText("Neuronios na camada intermediaria:");

        jLabel8.setText("Neuronios na camada de saida:");

        jTFNEntrada.setText("4");
        jTFNEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNEntradaActionPerformed(evt);
            }
        });

        jTFNIntermediaria.setText("9");
        jTFNIntermediaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNIntermediariaActionPerformed(evt);
            }
        });

        jTFNeuroniosSaida.setText("9");

        jBTDefinirNNeuronios.setText("Definir");
        jBTDefinirNNeuronios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTDefinirNNeuroniosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNeuroniosSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFNIntermediaria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jBTDefinirNNeuronios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFNEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFNIntermediaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFNeuroniosSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jBTDefinirNNeuronios)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jTPTreinamentoRede.addTab("Configurações", jPanel5);

        jLabel1.setText("Numero de treinamentos");

        jBTreinar.setText("Treinar");
        jBTreinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTreinarActionPerformed(evt);
            }
        });

        jButton2.setText("Zerar rede");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Taxa de erro atual:");

        jTFNumeroTreinamentosRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNumeroTreinamentosRealizadosActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de treinamentos realizados");

        jBTCarregaCSV.setText("Carregar CSV.");
        jBTCarregaCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTCarregaCSVActionPerformed(evt);
            }
        });

        jTFStatusCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFStatusCSVActionPerformed(evt);
            }
        });

        jLabel6.setText("Tempo em treinamento:");

        jTFTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTempoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBTCarregaCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFStatusCSV, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBTreinar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNumeroTreinamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(9, 9, 9)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFTempo, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jTFErro)
                    .addComponent(jTFNumeroTreinamentosRealizados))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNumeroTreinamentosRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBTCarregaCSV)
                            .addComponent(jTFStatusCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFNumeroTreinamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jBTreinar)))))
                    .addComponent(jTFTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        jTPTreinamentoRede.addTab("Treinamento da rede", jPanel2);

        jLabel5.setText("Dados para testar a rede:");

        jTFDadosTestarRede.setText("1,1,1,1");
        jTFDadosTestarRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDadosTestarRedeActionPerformed(evt);
            }
        });

        jTTestar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Neuronio", "Ativação"
            }
        ));
        jScrollPane1.setViewportView(jTTestar);

        jBtTestar.setText("Testar");
        jBtTestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtTestarActionPerformed(evt);
            }
        });

        jLFormatoTeste.setText("Formato: 0,0,0,0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTFDadosTestarRede, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLFormatoTeste))
                            .addComponent(jBtTestar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFDadosTestarRede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFormatoTeste))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtTestar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTPTreinamentoRede.addTab("Testes da rede", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTPTreinamentoRede)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jTPTreinamentoRede, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtTestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtTestarActionPerformed
        String dadosTeste = jTFDadosTestarRede.getText();
        String[] dados = dadosTeste.split(",");
        final Color[] cores = new Color[neuroniosSaida];
        if (dados.length != neuroniosEntrada) {
            JOptionPane.showMessageDialog(rootPane, "Dados para teste invalidos");

        } else {
            Double[] dataTest = new Double[neuroniosEntrada];
            for (int i = 0; i < neuroniosEntrada; i++) {
                dataTest[i] = Double.parseDouble(dados[i]);
            }

            rede.test(dataTest); //testar rede

            Double[] saida = rede.getOutput();

            DefaultTableModel tabelaModelo = (DefaultTableModel) jTTestar.getModel();
            tabelaModelo.setNumRows(0); //limpa a tabela
            for (int i = 0; i < saida.length; i++) {//seta cor
                tabelaModelo.addRow(new String[]{"Neuronio " + (i + 1), "" + formater.format(saida[i])});
                if (saida[i] > 0.5) {
                    cores[i] = Color.LIGHT_GRAY;
                }
                if (saida[i] > 0.7) {
                    cores[i] = Color.YELLOW;
                }
                if (saida[i] > 0.9) {
                    cores[i] = Color.RED;
                }
            }
        }
        jTTestar.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                c.setBackground(cores[row]);
                return c;
            }
        });
    }//GEN-LAST:event_jBtTestarActionPerformed

    private void jTFStatusCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFStatusCSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFStatusCSVActionPerformed

    private void jBTCarregaCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCarregaCSVActionPerformed
        try {

            LeitorCSV leitor = new LeitorCSV();
            ArrayList<Double[][]> dados = leitor.obterDados(neuroniosEntrada, neuroniosSaida); //dados para o treinamento
            dadosTreinamento = dados;
            jTFStatusCSV.setText("Arquivo CSV na memória");
        } catch (Exception e) {

            jTFStatusCSV.setText("Aguardando arquivo CSV");
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar CSV:" + e);
        }
    }//GEN-LAST:event_jBTCarregaCSVActionPerformed

    private void jTFNumeroTreinamentosRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNumeroTreinamentosRealizadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNumeroTreinamentosRealizadosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        zerarRede();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBTreinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTreinarActionPerformed
        int numeroTreinamentos = 0;
        if (!jTFStatusCSV.getText().equalsIgnoreCase("Aguardando arquivo CSV")) {
            try {
                numeroTreinamentos = Integer.parseInt(jTFNumeroTreinamentos.getText());
                if (numeroTreinamentos > 0) {
                    Double[][] patternInput = dadosTreinamento.get(0);
                    Double[][] expectedOutput = (Double[][]) dadosTreinamento.get(1);
                    rede.setTrainingData(patternInput, expectedOutput); //seta os dados para treinamento da rede
                    //contar o tempo do treinamento
                    long tempoInicio = System.currentTimeMillis();
                    double erro = rede.train(numeroTreinamentos); //treinamento
                    long tempoFinal = System.currentTimeMillis() - tempoInicio;
                    tempoExecucao += tempoFinal;
                    jTFTempo.setText(tempoExecucao + " ms");

                    jTFNumeroTreinamentosRealizados.setText("" + rede.getEpoch());
                    jTFErro.setText("" + formater.format(erro));
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Numero de treinamentos deve ser maior que 0");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Valor invalido para numero de treinamentos" + e);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Carregue o arquivo CSV primeiro!");

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTreinarActionPerformed

    private void jTFDadosTestarRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDadosTestarRedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDadosTestarRedeActionPerformed

    private void jTFTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTempoActionPerformed

    private void jTFNEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNEntradaActionPerformed

    private void jBTDefinirNNeuroniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTDefinirNNeuroniosActionPerformed
        try {
            definirNumeroNeuronios();
            zerarRede();
            iniciaComponentes();
            JOptionPane.showMessageDialog(rootPane, "Dados definidos com sucesso");
            jPanel2.requestFocus();
        } catch (Exception e) {
               JOptionPane.showMessageDialog(rootPane, "Erro ao definir dados "+e);
        }

    }//GEN-LAST:event_jBTDefinirNNeuroniosActionPerformed

    private void jTFNIntermediariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNIntermediariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNIntermediariaActionPerformed

    public void definirNumeroNeuronios() {

        try {

            neuroniosEntrada = Integer.parseInt(jTFNEntrada.getText());
            neuroniosIntermediaria = Integer.parseInt(jTFNIntermediaria.getText());
            neuroniosSaida = Integer.parseInt(jTFNeuroniosSaida.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Numero de neuronios invalidos");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTCarregaCSV;
    private javax.swing.JButton jBTDefinirNNeuronios;
    private javax.swing.JButton jBTreinar;
    private javax.swing.JButton jBtTestar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLFormatoTeste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDadosTestarRede;
    private javax.swing.JTextField jTFErro;
    private javax.swing.JTextField jTFNEntrada;
    private javax.swing.JTextField jTFNIntermediaria;
    private javax.swing.JTextField jTFNeuroniosSaida;
    private javax.swing.JTextField jTFNumeroTreinamentos;
    private javax.swing.JTextField jTFNumeroTreinamentosRealizados;
    private javax.swing.JTextField jTFStatusCSV;
    private javax.swing.JTextField jTFTempo;
    private javax.swing.JTabbedPane jTPTreinamentoRede;
    private javax.swing.JTable jTTestar;
    // End of variables declaration//GEN-END:variables
}
